[tools]
node = '22'

[settings]
# This must be enabled to make the hooks work
experimental = true

[tasks.dev]
description = 'Calls your dev script in `package.json`'
run = 'npm install && npm run dev'
